; GENERATED by tools/gen_proxy.py: each export jumps to the function of the real DLL in g_real
EXTERN g_real:QWORD
.CODE
D3DXAssembleShader PROC
    jmp qword ptr [g_real + 0]
D3DXAssembleShader ENDP
D3DXAssembleShaderFromFileA PROC
    jmp qword ptr [g_real + 8]
D3DXAssembleShaderFromFileA ENDP
D3DXAssembleShaderFromFileW PROC
    jmp qword ptr [g_real + 16]
D3DXAssembleShaderFromFileW ENDP
D3DXAssembleShaderFromResourceA PROC
    jmp qword ptr [g_real + 24]
D3DXAssembleShaderFromResourceA ENDP
D3DXAssembleShaderFromResourceW PROC
    jmp qword ptr [g_real + 32]
D3DXAssembleShaderFromResourceW ENDP
D3DXBoxBoundProbe PROC
    jmp qword ptr [g_real + 40]
D3DXBoxBoundProbe ENDP
D3DXCheckCubeTextureRequirements PROC
    jmp qword ptr [g_real + 48]
D3DXCheckCubeTextureRequirements ENDP
D3DXCheckTextureRequirements PROC
    jmp qword ptr [g_real + 56]
D3DXCheckTextureRequirements ENDP
D3DXCheckVersion PROC
    jmp qword ptr [g_real + 64]
D3DXCheckVersion ENDP
D3DXCheckVolumeTextureRequirements PROC
    jmp qword ptr [g_real + 72]
D3DXCheckVolumeTextureRequirements ENDP
D3DXCleanMesh PROC
    jmp qword ptr [g_real + 80]
D3DXCleanMesh ENDP
D3DXColorAdjustContrast PROC
    jmp qword ptr [g_real + 88]
D3DXColorAdjustContrast ENDP
D3DXColorAdjustSaturation PROC
    jmp qword ptr [g_real + 96]
D3DXColorAdjustSaturation ENDP
D3DXCompileShader PROC
    jmp qword ptr [g_real + 104]
D3DXCompileShader ENDP
D3DXCompileShaderFromFileA PROC
    jmp qword ptr [g_real + 112]
D3DXCompileShaderFromFileA ENDP
D3DXCompileShaderFromFileW PROC
    jmp qword ptr [g_real + 120]
D3DXCompileShaderFromFileW ENDP
D3DXCompileShaderFromResourceA PROC
    jmp qword ptr [g_real + 128]
D3DXCompileShaderFromResourceA ENDP
D3DXCompileShaderFromResourceW PROC
    jmp qword ptr [g_real + 136]
D3DXCompileShaderFromResourceW ENDP
D3DXComputeBoundingBox PROC
    jmp qword ptr [g_real + 144]
D3DXComputeBoundingBox ENDP
D3DXComputeBoundingSphere PROC
    jmp qword ptr [g_real + 152]
D3DXComputeBoundingSphere ENDP
D3DXComputeIMTFromPerTexelSignal PROC
    jmp qword ptr [g_real + 160]
D3DXComputeIMTFromPerTexelSignal ENDP
D3DXComputeIMTFromPerVertexSignal PROC
    jmp qword ptr [g_real + 168]
D3DXComputeIMTFromPerVertexSignal ENDP
D3DXComputeIMTFromSignal PROC
    jmp qword ptr [g_real + 176]
D3DXComputeIMTFromSignal ENDP
D3DXComputeIMTFromTexture PROC
    jmp qword ptr [g_real + 184]
D3DXComputeIMTFromTexture ENDP
D3DXComputeNormalMap PROC
    jmp qword ptr [g_real + 192]
D3DXComputeNormalMap ENDP
D3DXComputeNormals PROC
    jmp qword ptr [g_real + 200]
D3DXComputeNormals ENDP
D3DXComputeTangent PROC
    jmp qword ptr [g_real + 208]
D3DXComputeTangent ENDP
D3DXComputeTangentFrame PROC
    jmp qword ptr [g_real + 216]
D3DXComputeTangentFrame ENDP
D3DXComputeTangentFrameEx PROC
    jmp qword ptr [g_real + 224]
D3DXComputeTangentFrameEx ENDP
D3DXConcatenateMeshes PROC
    jmp qword ptr [g_real + 232]
D3DXConcatenateMeshes ENDP
D3DXConvertMeshSubsetToSingleStrip PROC
    jmp qword ptr [g_real + 240]
D3DXConvertMeshSubsetToSingleStrip ENDP
D3DXConvertMeshSubsetToStrips PROC
    jmp qword ptr [g_real + 248]
D3DXConvertMeshSubsetToStrips ENDP
D3DXCreateAnimationController PROC
    jmp qword ptr [g_real + 256]
D3DXCreateAnimationController ENDP
D3DXCreateBox PROC
    jmp qword ptr [g_real + 264]
D3DXCreateBox ENDP
D3DXCreateBuffer PROC
    jmp qword ptr [g_real + 272]
D3DXCreateBuffer ENDP
D3DXCreateCompressedAnimationSet PROC
    jmp qword ptr [g_real + 280]
D3DXCreateCompressedAnimationSet ENDP
D3DXCreateCubeTexture PROC
    jmp qword ptr [g_real + 288]
D3DXCreateCubeTexture ENDP
D3DXCreateCubeTextureFromFileA PROC
    jmp qword ptr [g_real + 296]
D3DXCreateCubeTextureFromFileA ENDP
D3DXCreateCubeTextureFromFileExA PROC
    jmp qword ptr [g_real + 304]
D3DXCreateCubeTextureFromFileExA ENDP
D3DXCreateCubeTextureFromFileExW PROC
    jmp qword ptr [g_real + 312]
D3DXCreateCubeTextureFromFileExW ENDP
D3DXCreateCubeTextureFromFileInMemory PROC
    jmp qword ptr [g_real + 320]
D3DXCreateCubeTextureFromFileInMemory ENDP
D3DXCreateCubeTextureFromFileInMemoryEx PROC
    jmp qword ptr [g_real + 328]
D3DXCreateCubeTextureFromFileInMemoryEx ENDP
D3DXCreateCubeTextureFromFileW PROC
    jmp qword ptr [g_real + 336]
D3DXCreateCubeTextureFromFileW ENDP
D3DXCreateCubeTextureFromResourceA PROC
    jmp qword ptr [g_real + 344]
D3DXCreateCubeTextureFromResourceA ENDP
D3DXCreateCubeTextureFromResourceExA PROC
    jmp qword ptr [g_real + 352]
D3DXCreateCubeTextureFromResourceExA ENDP
D3DXCreateCubeTextureFromResourceExW PROC
    jmp qword ptr [g_real + 360]
D3DXCreateCubeTextureFromResourceExW ENDP
D3DXCreateCubeTextureFromResourceW PROC
    jmp qword ptr [g_real + 368]
D3DXCreateCubeTextureFromResourceW ENDP
D3DXCreateCylinder PROC
    jmp qword ptr [g_real + 376]
D3DXCreateCylinder ENDP
D3DXCreateEffect PROC
    jmp qword ptr [g_real + 384]
D3DXCreateEffect ENDP
D3DXCreateEffectCompiler PROC
    jmp qword ptr [g_real + 392]
D3DXCreateEffectCompiler ENDP
D3DXCreateEffectCompilerFromFileA PROC
    jmp qword ptr [g_real + 400]
D3DXCreateEffectCompilerFromFileA ENDP
D3DXCreateEffectCompilerFromFileW PROC
    jmp qword ptr [g_real + 408]
D3DXCreateEffectCompilerFromFileW ENDP
D3DXCreateEffectCompilerFromResourceA PROC
    jmp qword ptr [g_real + 416]
D3DXCreateEffectCompilerFromResourceA ENDP
D3DXCreateEffectCompilerFromResourceW PROC
    jmp qword ptr [g_real + 424]
D3DXCreateEffectCompilerFromResourceW ENDP
D3DXCreateEffectEx PROC
    jmp qword ptr [g_real + 432]
D3DXCreateEffectEx ENDP
D3DXCreateEffectFromFileA PROC
    jmp qword ptr [g_real + 440]
D3DXCreateEffectFromFileA ENDP
D3DXCreateEffectFromFileExA PROC
    jmp qword ptr [g_real + 448]
D3DXCreateEffectFromFileExA ENDP
D3DXCreateEffectFromFileExW PROC
    jmp qword ptr [g_real + 456]
D3DXCreateEffectFromFileExW ENDP
D3DXCreateEffectFromFileW PROC
    jmp qword ptr [g_real + 464]
D3DXCreateEffectFromFileW ENDP
D3DXCreateEffectFromResourceA PROC
    jmp qword ptr [g_real + 472]
D3DXCreateEffectFromResourceA ENDP
D3DXCreateEffectFromResourceExA PROC
    jmp qword ptr [g_real + 480]
D3DXCreateEffectFromResourceExA ENDP
D3DXCreateEffectFromResourceExW PROC
    jmp qword ptr [g_real + 488]
D3DXCreateEffectFromResourceExW ENDP
D3DXCreateEffectFromResourceW PROC
    jmp qword ptr [g_real + 496]
D3DXCreateEffectFromResourceW ENDP
D3DXCreateEffectPool PROC
    jmp qword ptr [g_real + 504]
D3DXCreateEffectPool ENDP
D3DXCreateFontA PROC
    jmp qword ptr [g_real + 512]
D3DXCreateFontA ENDP
D3DXCreateFontIndirectA PROC
    jmp qword ptr [g_real + 520]
D3DXCreateFontIndirectA ENDP
D3DXCreateFontIndirectW PROC
    jmp qword ptr [g_real + 528]
D3DXCreateFontIndirectW ENDP
D3DXCreateFontW PROC
    jmp qword ptr [g_real + 536]
D3DXCreateFontW ENDP
D3DXCreateKeyframedAnimationSet PROC
    jmp qword ptr [g_real + 544]
D3DXCreateKeyframedAnimationSet ENDP
D3DXCreateLine PROC
    jmp qword ptr [g_real + 552]
D3DXCreateLine ENDP
D3DXCreateMatrixStack PROC
    jmp qword ptr [g_real + 560]
D3DXCreateMatrixStack ENDP
D3DXCreateMesh PROC
    jmp qword ptr [g_real + 568]
D3DXCreateMesh ENDP
D3DXCreateMeshFVF PROC
    jmp qword ptr [g_real + 576]
D3DXCreateMeshFVF ENDP
D3DXCreateNPatchMesh PROC
    jmp qword ptr [g_real + 584]
D3DXCreateNPatchMesh ENDP
D3DXCreatePMeshFromStream PROC
    jmp qword ptr [g_real + 592]
D3DXCreatePMeshFromStream ENDP
D3DXCreatePRTBuffer PROC
    jmp qword ptr [g_real + 600]
D3DXCreatePRTBuffer ENDP
D3DXCreatePRTBufferTex PROC
    jmp qword ptr [g_real + 608]
D3DXCreatePRTBufferTex ENDP
D3DXCreatePRTCompBuffer PROC
    jmp qword ptr [g_real + 616]
D3DXCreatePRTCompBuffer ENDP
D3DXCreatePRTEngine PROC
    jmp qword ptr [g_real + 624]
D3DXCreatePRTEngine ENDP
D3DXCreatePatchMesh PROC
    jmp qword ptr [g_real + 632]
D3DXCreatePatchMesh ENDP
D3DXCreatePolygon PROC
    jmp qword ptr [g_real + 640]
D3DXCreatePolygon ENDP
D3DXCreateRenderToEnvMap PROC
    jmp qword ptr [g_real + 648]
D3DXCreateRenderToEnvMap ENDP
D3DXCreateRenderToSurface PROC
    jmp qword ptr [g_real + 656]
D3DXCreateRenderToSurface ENDP
D3DXCreateSPMesh PROC
    jmp qword ptr [g_real + 664]
D3DXCreateSPMesh ENDP
D3DXCreateSkinInfo PROC
    jmp qword ptr [g_real + 672]
D3DXCreateSkinInfo ENDP
D3DXCreateSkinInfoFVF PROC
    jmp qword ptr [g_real + 680]
D3DXCreateSkinInfoFVF ENDP
D3DXCreateSkinInfoFromBlendedMesh PROC
    jmp qword ptr [g_real + 688]
D3DXCreateSkinInfoFromBlendedMesh ENDP
D3DXCreateSphere PROC
    jmp qword ptr [g_real + 696]
D3DXCreateSphere ENDP
D3DXCreateSprite PROC
    jmp qword ptr [g_real + 704]
D3DXCreateSprite ENDP
D3DXCreateTeapot PROC
    jmp qword ptr [g_real + 712]
D3DXCreateTeapot ENDP
D3DXCreateTextA PROC
    jmp qword ptr [g_real + 720]
D3DXCreateTextA ENDP
D3DXCreateTextW PROC
    jmp qword ptr [g_real + 728]
D3DXCreateTextW ENDP
D3DXCreateTexture PROC
    jmp qword ptr [g_real + 736]
D3DXCreateTexture ENDP
D3DXCreateTextureFromFileA PROC
    jmp qword ptr [g_real + 744]
D3DXCreateTextureFromFileA ENDP
D3DXCreateTextureFromFileExA PROC
    jmp qword ptr [g_real + 752]
D3DXCreateTextureFromFileExA ENDP
D3DXCreateTextureFromFileExW PROC
    jmp qword ptr [g_real + 760]
D3DXCreateTextureFromFileExW ENDP
D3DXCreateTextureFromFileInMemory PROC
    jmp qword ptr [g_real + 768]
D3DXCreateTextureFromFileInMemory ENDP
D3DXCreateTextureFromFileInMemoryEx PROC
    jmp qword ptr [g_real + 776]
D3DXCreateTextureFromFileInMemoryEx ENDP
D3DXCreateTextureFromFileW PROC
    jmp qword ptr [g_real + 784]
D3DXCreateTextureFromFileW ENDP
D3DXCreateTextureFromResourceA PROC
    jmp qword ptr [g_real + 792]
D3DXCreateTextureFromResourceA ENDP
D3DXCreateTextureFromResourceExA PROC
    jmp qword ptr [g_real + 800]
D3DXCreateTextureFromResourceExA ENDP
D3DXCreateTextureFromResourceExW PROC
    jmp qword ptr [g_real + 808]
D3DXCreateTextureFromResourceExW ENDP
D3DXCreateTextureFromResourceW PROC
    jmp qword ptr [g_real + 816]
D3DXCreateTextureFromResourceW ENDP
D3DXCreateTextureGutterHelper PROC
    jmp qword ptr [g_real + 824]
D3DXCreateTextureGutterHelper ENDP
D3DXCreateTextureShader PROC
    jmp qword ptr [g_real + 832]
D3DXCreateTextureShader ENDP
D3DXCreateTorus PROC
    jmp qword ptr [g_real + 840]
D3DXCreateTorus ENDP
D3DXCreateVolumeTexture PROC
    jmp qword ptr [g_real + 848]
D3DXCreateVolumeTexture ENDP
D3DXCreateVolumeTextureFromFileA PROC
    jmp qword ptr [g_real + 856]
D3DXCreateVolumeTextureFromFileA ENDP
D3DXCreateVolumeTextureFromFileExA PROC
    jmp qword ptr [g_real + 864]
D3DXCreateVolumeTextureFromFileExA ENDP
D3DXCreateVolumeTextureFromFileExW PROC
    jmp qword ptr [g_real + 872]
D3DXCreateVolumeTextureFromFileExW ENDP
D3DXCreateVolumeTextureFromFileInMemory PROC
    jmp qword ptr [g_real + 880]
D3DXCreateVolumeTextureFromFileInMemory ENDP
D3DXCreateVolumeTextureFromFileInMemoryEx PROC
    jmp qword ptr [g_real + 888]
D3DXCreateVolumeTextureFromFileInMemoryEx ENDP
D3DXCreateVolumeTextureFromFileW PROC
    jmp qword ptr [g_real + 896]
D3DXCreateVolumeTextureFromFileW ENDP
D3DXCreateVolumeTextureFromResourceA PROC
    jmp qword ptr [g_real + 904]
D3DXCreateVolumeTextureFromResourceA ENDP
D3DXCreateVolumeTextureFromResourceExA PROC
    jmp qword ptr [g_real + 912]
D3DXCreateVolumeTextureFromResourceExA ENDP
D3DXCreateVolumeTextureFromResourceExW PROC
    jmp qword ptr [g_real + 920]
D3DXCreateVolumeTextureFromResourceExW ENDP
D3DXCreateVolumeTextureFromResourceW PROC
    jmp qword ptr [g_real + 928]
D3DXCreateVolumeTextureFromResourceW ENDP
D3DXDebugMute PROC
    jmp qword ptr [g_real + 936]
D3DXDebugMute ENDP
D3DXDeclaratorFromFVF PROC
    jmp qword ptr [g_real + 944]
D3DXDeclaratorFromFVF ENDP
D3DXDisassembleEffect PROC
    jmp qword ptr [g_real + 952]
D3DXDisassembleEffect ENDP
D3DXDisassembleShader PROC
    jmp qword ptr [g_real + 960]
D3DXDisassembleShader ENDP
D3DXFVFFromDeclarator PROC
    jmp qword ptr [g_real + 968]
D3DXFVFFromDeclarator ENDP
D3DXFileCreate PROC
    jmp qword ptr [g_real + 976]
D3DXFileCreate ENDP
D3DXFillCubeTexture PROC
    jmp qword ptr [g_real + 984]
D3DXFillCubeTexture ENDP
D3DXFillCubeTextureTX PROC
    jmp qword ptr [g_real + 992]
D3DXFillCubeTextureTX ENDP
D3DXFillTexture PROC
    jmp qword ptr [g_real + 1000]
D3DXFillTexture ENDP
D3DXFillTextureTX PROC
    jmp qword ptr [g_real + 1008]
D3DXFillTextureTX ENDP
D3DXFillVolumeTexture PROC
    jmp qword ptr [g_real + 1016]
D3DXFillVolumeTexture ENDP
D3DXFillVolumeTextureTX PROC
    jmp qword ptr [g_real + 1024]
D3DXFillVolumeTextureTX ENDP
D3DXFilterTexture PROC
    jmp qword ptr [g_real + 1032]
D3DXFilterTexture ENDP
D3DXFindShaderComment PROC
    jmp qword ptr [g_real + 1040]
D3DXFindShaderComment ENDP
D3DXFloat16To32Array PROC
    jmp qword ptr [g_real + 1048]
D3DXFloat16To32Array ENDP
D3DXFloat32To16Array PROC
    jmp qword ptr [g_real + 1056]
D3DXFloat32To16Array ENDP
D3DXFrameAppendChild PROC
    jmp qword ptr [g_real + 1064]
D3DXFrameAppendChild ENDP
D3DXFrameCalculateBoundingSphere PROC
    jmp qword ptr [g_real + 1072]
D3DXFrameCalculateBoundingSphere ENDP
D3DXFrameDestroy PROC
    jmp qword ptr [g_real + 1080]
D3DXFrameDestroy ENDP
D3DXFrameFind PROC
    jmp qword ptr [g_real + 1088]
D3DXFrameFind ENDP
D3DXFrameNumNamedMatrices PROC
    jmp qword ptr [g_real + 1096]
D3DXFrameNumNamedMatrices ENDP
D3DXFrameRegisterNamedMatrices PROC
    jmp qword ptr [g_real + 1104]
D3DXFrameRegisterNamedMatrices ENDP
D3DXFresnelTerm PROC
    jmp qword ptr [g_real + 1112]
D3DXFresnelTerm ENDP
D3DXGenerateOutputDecl PROC
    jmp qword ptr [g_real + 1120]
D3DXGenerateOutputDecl ENDP
D3DXGeneratePMesh PROC
    jmp qword ptr [g_real + 1128]
D3DXGeneratePMesh ENDP
D3DXGetDeclLength PROC
    jmp qword ptr [g_real + 1136]
D3DXGetDeclLength ENDP
D3DXGetDeclVertexSize PROC
    jmp qword ptr [g_real + 1144]
D3DXGetDeclVertexSize ENDP
D3DXGetDriverLevel PROC
    jmp qword ptr [g_real + 1152]
D3DXGetDriverLevel ENDP
D3DXGetFVFVertexSize PROC
    jmp qword ptr [g_real + 1160]
D3DXGetFVFVertexSize ENDP
D3DXGetImageInfoFromFileA PROC
    jmp qword ptr [g_real + 1168]
D3DXGetImageInfoFromFileA ENDP
D3DXGetImageInfoFromFileInMemory PROC
    jmp qword ptr [g_real + 1176]
D3DXGetImageInfoFromFileInMemory ENDP
D3DXGetImageInfoFromFileW PROC
    jmp qword ptr [g_real + 1184]
D3DXGetImageInfoFromFileW ENDP
D3DXGetImageInfoFromResourceA PROC
    jmp qword ptr [g_real + 1192]
D3DXGetImageInfoFromResourceA ENDP
D3DXGetImageInfoFromResourceW PROC
    jmp qword ptr [g_real + 1200]
D3DXGetImageInfoFromResourceW ENDP
D3DXGetPixelShaderProfile PROC
    jmp qword ptr [g_real + 1208]
D3DXGetPixelShaderProfile ENDP
D3DXGetShaderConstantTable PROC
    jmp qword ptr [g_real + 1216]
D3DXGetShaderConstantTable ENDP
D3DXGetShaderConstantTableEx PROC
    jmp qword ptr [g_real + 1224]
D3DXGetShaderConstantTableEx ENDP
D3DXGetShaderInputSemantics PROC
    jmp qword ptr [g_real + 1232]
D3DXGetShaderInputSemantics ENDP
D3DXGetShaderOutputSemantics PROC
    jmp qword ptr [g_real + 1240]
D3DXGetShaderOutputSemantics ENDP
D3DXGetShaderSamplers PROC
    jmp qword ptr [g_real + 1248]
D3DXGetShaderSamplers ENDP
D3DXGetShaderSize PROC
    jmp qword ptr [g_real + 1256]
D3DXGetShaderSize ENDP
D3DXGetShaderVersion PROC
    jmp qword ptr [g_real + 1264]
D3DXGetShaderVersion ENDP
D3DXGetVertexShaderProfile PROC
    jmp qword ptr [g_real + 1272]
D3DXGetVertexShaderProfile ENDP
D3DXIntersect PROC
    jmp qword ptr [g_real + 1280]
D3DXIntersect ENDP
D3DXIntersectSubset PROC
    jmp qword ptr [g_real + 1288]
D3DXIntersectSubset ENDP
D3DXIntersectTri PROC
    jmp qword ptr [g_real + 1296]
D3DXIntersectTri ENDP
D3DXLoadMeshFromXA PROC
    jmp qword ptr [g_real + 1304]
D3DXLoadMeshFromXA ENDP
D3DXLoadMeshFromXInMemory PROC
    jmp qword ptr [g_real + 1312]
D3DXLoadMeshFromXInMemory ENDP
D3DXLoadMeshFromXResource PROC
    jmp qword ptr [g_real + 1320]
D3DXLoadMeshFromXResource ENDP
D3DXLoadMeshFromXW PROC
    jmp qword ptr [g_real + 1328]
D3DXLoadMeshFromXW ENDP
D3DXLoadMeshFromXof PROC
    jmp qword ptr [g_real + 1336]
D3DXLoadMeshFromXof ENDP
D3DXLoadMeshHierarchyFromXA PROC
    jmp qword ptr [g_real + 1344]
D3DXLoadMeshHierarchyFromXA ENDP
D3DXLoadMeshHierarchyFromXInMemory PROC
    jmp qword ptr [g_real + 1352]
D3DXLoadMeshHierarchyFromXInMemory ENDP
D3DXLoadMeshHierarchyFromXW PROC
    jmp qword ptr [g_real + 1360]
D3DXLoadMeshHierarchyFromXW ENDP
D3DXLoadPRTBufferFromFileA PROC
    jmp qword ptr [g_real + 1368]
D3DXLoadPRTBufferFromFileA ENDP
D3DXLoadPRTBufferFromFileW PROC
    jmp qword ptr [g_real + 1376]
D3DXLoadPRTBufferFromFileW ENDP
D3DXLoadPRTCompBufferFromFileA PROC
    jmp qword ptr [g_real + 1384]
D3DXLoadPRTCompBufferFromFileA ENDP
D3DXLoadPRTCompBufferFromFileW PROC
    jmp qword ptr [g_real + 1392]
D3DXLoadPRTCompBufferFromFileW ENDP
D3DXLoadPatchMeshFromXof PROC
    jmp qword ptr [g_real + 1400]
D3DXLoadPatchMeshFromXof ENDP
D3DXLoadSkinMeshFromXof PROC
    jmp qword ptr [g_real + 1408]
D3DXLoadSkinMeshFromXof ENDP
D3DXLoadSurfaceFromFileA PROC
    jmp qword ptr [g_real + 1416]
D3DXLoadSurfaceFromFileA ENDP
D3DXLoadSurfaceFromFileInMemory PROC
    jmp qword ptr [g_real + 1424]
D3DXLoadSurfaceFromFileInMemory ENDP
D3DXLoadSurfaceFromFileW PROC
    jmp qword ptr [g_real + 1432]
D3DXLoadSurfaceFromFileW ENDP
D3DXLoadSurfaceFromMemory PROC
    jmp qword ptr [g_real + 1440]
D3DXLoadSurfaceFromMemory ENDP
D3DXLoadSurfaceFromResourceA PROC
    jmp qword ptr [g_real + 1448]
D3DXLoadSurfaceFromResourceA ENDP
D3DXLoadSurfaceFromResourceW PROC
    jmp qword ptr [g_real + 1456]
D3DXLoadSurfaceFromResourceW ENDP
D3DXLoadSurfaceFromSurface PROC
    jmp qword ptr [g_real + 1464]
D3DXLoadSurfaceFromSurface ENDP
D3DXLoadVolumeFromFileA PROC
    jmp qword ptr [g_real + 1472]
D3DXLoadVolumeFromFileA ENDP
D3DXLoadVolumeFromFileInMemory PROC
    jmp qword ptr [g_real + 1480]
D3DXLoadVolumeFromFileInMemory ENDP
D3DXLoadVolumeFromFileW PROC
    jmp qword ptr [g_real + 1488]
D3DXLoadVolumeFromFileW ENDP
D3DXLoadVolumeFromMemory PROC
    jmp qword ptr [g_real + 1496]
D3DXLoadVolumeFromMemory ENDP
D3DXLoadVolumeFromResourceA PROC
    jmp qword ptr [g_real + 1504]
D3DXLoadVolumeFromResourceA ENDP
D3DXLoadVolumeFromResourceW PROC
    jmp qword ptr [g_real + 1512]
D3DXLoadVolumeFromResourceW ENDP
D3DXLoadVolumeFromVolume PROC
    jmp qword ptr [g_real + 1520]
D3DXLoadVolumeFromVolume ENDP
D3DXMatrixAffineTransformation PROC
    jmp qword ptr [g_real + 1528]
D3DXMatrixAffineTransformation ENDP
D3DXMatrixAffineTransformation2D PROC
    jmp qword ptr [g_real + 1536]
D3DXMatrixAffineTransformation2D ENDP
D3DXMatrixDecompose PROC
    jmp qword ptr [g_real + 1544]
D3DXMatrixDecompose ENDP
D3DXMatrixDeterminant PROC
    jmp qword ptr [g_real + 1552]
D3DXMatrixDeterminant ENDP
D3DXMatrixInverse PROC
    jmp qword ptr [g_real + 1560]
D3DXMatrixInverse ENDP
D3DXMatrixLookAtLH PROC
    jmp qword ptr [g_real + 1568]
D3DXMatrixLookAtLH ENDP
D3DXMatrixLookAtRH PROC
    jmp qword ptr [g_real + 1576]
D3DXMatrixLookAtRH ENDP
D3DXMatrixMultiply PROC
    jmp qword ptr [g_real + 1584]
D3DXMatrixMultiply ENDP
D3DXMatrixMultiplyTranspose PROC
    jmp qword ptr [g_real + 1592]
D3DXMatrixMultiplyTranspose ENDP
D3DXMatrixOrthoLH PROC
    jmp qword ptr [g_real + 1600]
D3DXMatrixOrthoLH ENDP
D3DXMatrixOrthoOffCenterLH PROC
    jmp qword ptr [g_real + 1608]
D3DXMatrixOrthoOffCenterLH ENDP
D3DXMatrixOrthoOffCenterRH PROC
    jmp qword ptr [g_real + 1616]
D3DXMatrixOrthoOffCenterRH ENDP
D3DXMatrixOrthoRH PROC
    jmp qword ptr [g_real + 1624]
D3DXMatrixOrthoRH ENDP
D3DXMatrixPerspectiveFovLH PROC
    jmp qword ptr [g_real + 1632]
D3DXMatrixPerspectiveFovLH ENDP
D3DXMatrixPerspectiveFovRH PROC
    jmp qword ptr [g_real + 1640]
D3DXMatrixPerspectiveFovRH ENDP
D3DXMatrixPerspectiveLH PROC
    jmp qword ptr [g_real + 1648]
D3DXMatrixPerspectiveLH ENDP
D3DXMatrixPerspectiveOffCenterLH PROC
    jmp qword ptr [g_real + 1656]
D3DXMatrixPerspectiveOffCenterLH ENDP
D3DXMatrixPerspectiveOffCenterRH PROC
    jmp qword ptr [g_real + 1664]
D3DXMatrixPerspectiveOffCenterRH ENDP
D3DXMatrixPerspectiveRH PROC
    jmp qword ptr [g_real + 1672]
D3DXMatrixPerspectiveRH ENDP
D3DXMatrixReflect PROC
    jmp qword ptr [g_real + 1680]
D3DXMatrixReflect ENDP
D3DXMatrixRotationAxis PROC
    jmp qword ptr [g_real + 1688]
D3DXMatrixRotationAxis ENDP
D3DXMatrixRotationQuaternion PROC
    jmp qword ptr [g_real + 1696]
D3DXMatrixRotationQuaternion ENDP
D3DXMatrixRotationX PROC
    jmp qword ptr [g_real + 1704]
D3DXMatrixRotationX ENDP
D3DXMatrixRotationY PROC
    jmp qword ptr [g_real + 1712]
D3DXMatrixRotationY ENDP
D3DXMatrixRotationYawPitchRoll PROC
    jmp qword ptr [g_real + 1720]
D3DXMatrixRotationYawPitchRoll ENDP
D3DXMatrixRotationZ PROC
    jmp qword ptr [g_real + 1728]
D3DXMatrixRotationZ ENDP
D3DXMatrixScaling PROC
    jmp qword ptr [g_real + 1736]
D3DXMatrixScaling ENDP
D3DXMatrixShadow PROC
    jmp qword ptr [g_real + 1744]
D3DXMatrixShadow ENDP
D3DXMatrixTransformation PROC
    jmp qword ptr [g_real + 1752]
D3DXMatrixTransformation ENDP
D3DXMatrixTransformation2D PROC
    jmp qword ptr [g_real + 1760]
D3DXMatrixTransformation2D ENDP
D3DXMatrixTranslation PROC
    jmp qword ptr [g_real + 1768]
D3DXMatrixTranslation ENDP
D3DXMatrixTranspose PROC
    jmp qword ptr [g_real + 1776]
D3DXMatrixTranspose ENDP
D3DXOptimizeFaces PROC
    jmp qword ptr [g_real + 1784]
D3DXOptimizeFaces ENDP
D3DXOptimizeVertices PROC
    jmp qword ptr [g_real + 1792]
D3DXOptimizeVertices ENDP
D3DXPlaneFromPointNormal PROC
    jmp qword ptr [g_real + 1800]
D3DXPlaneFromPointNormal ENDP
D3DXPlaneFromPoints PROC
    jmp qword ptr [g_real + 1808]
D3DXPlaneFromPoints ENDP
D3DXPlaneIntersectLine PROC
    jmp qword ptr [g_real + 1816]
D3DXPlaneIntersectLine ENDP
D3DXPlaneNormalize PROC
    jmp qword ptr [g_real + 1824]
D3DXPlaneNormalize ENDP
D3DXPlaneTransform PROC
    jmp qword ptr [g_real + 1832]
D3DXPlaneTransform ENDP
D3DXPlaneTransformArray PROC
    jmp qword ptr [g_real + 1840]
D3DXPlaneTransformArray ENDP
D3DXPreprocessShader PROC
    jmp qword ptr [g_real + 1848]
D3DXPreprocessShader ENDP
D3DXPreprocessShaderFromFileA PROC
    jmp qword ptr [g_real + 1856]
D3DXPreprocessShaderFromFileA ENDP
D3DXPreprocessShaderFromFileW PROC
    jmp qword ptr [g_real + 1864]
D3DXPreprocessShaderFromFileW ENDP
D3DXPreprocessShaderFromResourceA PROC
    jmp qword ptr [g_real + 1872]
D3DXPreprocessShaderFromResourceA ENDP
D3DXPreprocessShaderFromResourceW PROC
    jmp qword ptr [g_real + 1880]
D3DXPreprocessShaderFromResourceW ENDP
D3DXQuaternionBaryCentric PROC
    jmp qword ptr [g_real + 1888]
D3DXQuaternionBaryCentric ENDP
D3DXQuaternionExp PROC
    jmp qword ptr [g_real + 1896]
D3DXQuaternionExp ENDP
D3DXQuaternionInverse PROC
    jmp qword ptr [g_real + 1904]
D3DXQuaternionInverse ENDP
D3DXQuaternionLn PROC
    jmp qword ptr [g_real + 1912]
D3DXQuaternionLn ENDP
D3DXQuaternionMultiply PROC
    jmp qword ptr [g_real + 1920]
D3DXQuaternionMultiply ENDP
D3DXQuaternionNormalize PROC
    jmp qword ptr [g_real + 1928]
D3DXQuaternionNormalize ENDP
D3DXQuaternionRotationAxis PROC
    jmp qword ptr [g_real + 1936]
D3DXQuaternionRotationAxis ENDP
D3DXQuaternionRotationMatrix PROC
    jmp qword ptr [g_real + 1944]
D3DXQuaternionRotationMatrix ENDP
D3DXQuaternionRotationYawPitchRoll PROC
    jmp qword ptr [g_real + 1952]
D3DXQuaternionRotationYawPitchRoll ENDP
D3DXQuaternionSlerp PROC
    jmp qword ptr [g_real + 1960]
D3DXQuaternionSlerp ENDP
D3DXQuaternionSquad PROC
    jmp qword ptr [g_real + 1968]
D3DXQuaternionSquad ENDP
D3DXQuaternionSquadSetup PROC
    jmp qword ptr [g_real + 1976]
D3DXQuaternionSquadSetup ENDP
D3DXQuaternionToAxisAngle PROC
    jmp qword ptr [g_real + 1984]
D3DXQuaternionToAxisAngle ENDP
D3DXRectPatchSize PROC
    jmp qword ptr [g_real + 1992]
D3DXRectPatchSize ENDP
D3DXSHAdd PROC
    jmp qword ptr [g_real + 2000]
D3DXSHAdd ENDP
D3DXSHDot PROC
    jmp qword ptr [g_real + 2008]
D3DXSHDot ENDP
D3DXSHEvalConeLight PROC
    jmp qword ptr [g_real + 2016]
D3DXSHEvalConeLight ENDP
D3DXSHEvalDirection PROC
    jmp qword ptr [g_real + 2024]
D3DXSHEvalDirection ENDP
D3DXSHEvalDirectionalLight PROC
    jmp qword ptr [g_real + 2032]
D3DXSHEvalDirectionalLight ENDP
D3DXSHEvalHemisphereLight PROC
    jmp qword ptr [g_real + 2040]
D3DXSHEvalHemisphereLight ENDP
D3DXSHEvalSphericalLight PROC
    jmp qword ptr [g_real + 2048]
D3DXSHEvalSphericalLight ENDP
D3DXSHMultiply2 PROC
    jmp qword ptr [g_real + 2056]
D3DXSHMultiply2 ENDP
D3DXSHMultiply3 PROC
    jmp qword ptr [g_real + 2064]
D3DXSHMultiply3 ENDP
D3DXSHMultiply4 PROC
    jmp qword ptr [g_real + 2072]
D3DXSHMultiply4 ENDP
D3DXSHMultiply5 PROC
    jmp qword ptr [g_real + 2080]
D3DXSHMultiply5 ENDP
D3DXSHMultiply6 PROC
    jmp qword ptr [g_real + 2088]
D3DXSHMultiply6 ENDP
D3DXSHPRTCompSplitMeshSC PROC
    jmp qword ptr [g_real + 2096]
D3DXSHPRTCompSplitMeshSC ENDP
D3DXSHPRTCompSuperCluster PROC
    jmp qword ptr [g_real + 2104]
D3DXSHPRTCompSuperCluster ENDP
D3DXSHProjectCubeMap PROC
    jmp qword ptr [g_real + 2112]
D3DXSHProjectCubeMap ENDP
D3DXSHRotate PROC
    jmp qword ptr [g_real + 2120]
D3DXSHRotate ENDP
D3DXSHRotateZ PROC
    jmp qword ptr [g_real + 2128]
D3DXSHRotateZ ENDP
D3DXSHScale PROC
    jmp qword ptr [g_real + 2136]
D3DXSHScale ENDP
D3DXSaveMeshHierarchyToFileA PROC
    jmp qword ptr [g_real + 2144]
D3DXSaveMeshHierarchyToFileA ENDP
D3DXSaveMeshHierarchyToFileW PROC
    jmp qword ptr [g_real + 2152]
D3DXSaveMeshHierarchyToFileW ENDP
D3DXSaveMeshToXA PROC
    jmp qword ptr [g_real + 2160]
D3DXSaveMeshToXA ENDP
D3DXSaveMeshToXW PROC
    jmp qword ptr [g_real + 2168]
D3DXSaveMeshToXW ENDP
D3DXSavePRTBufferToFileA PROC
    jmp qword ptr [g_real + 2176]
D3DXSavePRTBufferToFileA ENDP
D3DXSavePRTBufferToFileW PROC
    jmp qword ptr [g_real + 2184]
D3DXSavePRTBufferToFileW ENDP
D3DXSavePRTCompBufferToFileA PROC
    jmp qword ptr [g_real + 2192]
D3DXSavePRTCompBufferToFileA ENDP
D3DXSavePRTCompBufferToFileW PROC
    jmp qword ptr [g_real + 2200]
D3DXSavePRTCompBufferToFileW ENDP
D3DXSaveSurfaceToFileA PROC
    jmp qword ptr [g_real + 2208]
D3DXSaveSurfaceToFileA ENDP
D3DXSaveSurfaceToFileInMemory PROC
    jmp qword ptr [g_real + 2216]
D3DXSaveSurfaceToFileInMemory ENDP
D3DXSaveSurfaceToFileW PROC
    jmp qword ptr [g_real + 2224]
D3DXSaveSurfaceToFileW ENDP
D3DXSaveTextureToFileA PROC
    jmp qword ptr [g_real + 2232]
D3DXSaveTextureToFileA ENDP
D3DXSaveTextureToFileInMemory PROC
    jmp qword ptr [g_real + 2240]
D3DXSaveTextureToFileInMemory ENDP
D3DXSaveTextureToFileW PROC
    jmp qword ptr [g_real + 2248]
D3DXSaveTextureToFileW ENDP
D3DXSaveVolumeToFileA PROC
    jmp qword ptr [g_real + 2256]
D3DXSaveVolumeToFileA ENDP
D3DXSaveVolumeToFileInMemory PROC
    jmp qword ptr [g_real + 2264]
D3DXSaveVolumeToFileInMemory ENDP
D3DXSaveVolumeToFileW PROC
    jmp qword ptr [g_real + 2272]
D3DXSaveVolumeToFileW ENDP
D3DXSimplifyMesh PROC
    jmp qword ptr [g_real + 2280]
D3DXSimplifyMesh ENDP
D3DXSphereBoundProbe PROC
    jmp qword ptr [g_real + 2288]
D3DXSphereBoundProbe ENDP
D3DXSplitMesh PROC
    jmp qword ptr [g_real + 2296]
D3DXSplitMesh ENDP
D3DXTessellateNPatches PROC
    jmp qword ptr [g_real + 2304]
D3DXTessellateNPatches ENDP
D3DXTessellateRectPatch PROC
    jmp qword ptr [g_real + 2312]
D3DXTessellateRectPatch ENDP
D3DXTessellateTriPatch PROC
    jmp qword ptr [g_real + 2320]
D3DXTessellateTriPatch ENDP
D3DXTriPatchSize PROC
    jmp qword ptr [g_real + 2328]
D3DXTriPatchSize ENDP
D3DXUVAtlasCreate PROC
    jmp qword ptr [g_real + 2336]
D3DXUVAtlasCreate ENDP
D3DXUVAtlasPack PROC
    jmp qword ptr [g_real + 2344]
D3DXUVAtlasPack ENDP
D3DXUVAtlasPartition PROC
    jmp qword ptr [g_real + 2352]
D3DXUVAtlasPartition ENDP
D3DXValidMesh PROC
    jmp qword ptr [g_real + 2360]
D3DXValidMesh ENDP
D3DXValidPatchMesh PROC
    jmp qword ptr [g_real + 2368]
D3DXValidPatchMesh ENDP
D3DXVec2BaryCentric PROC
    jmp qword ptr [g_real + 2376]
D3DXVec2BaryCentric ENDP
D3DXVec2CatmullRom PROC
    jmp qword ptr [g_real + 2384]
D3DXVec2CatmullRom ENDP
D3DXVec2Hermite PROC
    jmp qword ptr [g_real + 2392]
D3DXVec2Hermite ENDP
D3DXVec2Normalize PROC
    jmp qword ptr [g_real + 2400]
D3DXVec2Normalize ENDP
D3DXVec2Transform PROC
    jmp qword ptr [g_real + 2408]
D3DXVec2Transform ENDP
D3DXVec2TransformArray PROC
    jmp qword ptr [g_real + 2416]
D3DXVec2TransformArray ENDP
D3DXVec2TransformCoord PROC
    jmp qword ptr [g_real + 2424]
D3DXVec2TransformCoord ENDP
D3DXVec2TransformCoordArray PROC
    jmp qword ptr [g_real + 2432]
D3DXVec2TransformCoordArray ENDP
D3DXVec2TransformNormal PROC
    jmp qword ptr [g_real + 2440]
D3DXVec2TransformNormal ENDP
D3DXVec2TransformNormalArray PROC
    jmp qword ptr [g_real + 2448]
D3DXVec2TransformNormalArray ENDP
D3DXVec3BaryCentric PROC
    jmp qword ptr [g_real + 2456]
D3DXVec3BaryCentric ENDP
D3DXVec3CatmullRom PROC
    jmp qword ptr [g_real + 2464]
D3DXVec3CatmullRom ENDP
D3DXVec3Hermite PROC
    jmp qword ptr [g_real + 2472]
D3DXVec3Hermite ENDP
D3DXVec3Normalize PROC
    jmp qword ptr [g_real + 2480]
D3DXVec3Normalize ENDP
D3DXVec3Project PROC
    jmp qword ptr [g_real + 2488]
D3DXVec3Project ENDP
D3DXVec3ProjectArray PROC
    jmp qword ptr [g_real + 2496]
D3DXVec3ProjectArray ENDP
D3DXVec3Transform PROC
    jmp qword ptr [g_real + 2504]
D3DXVec3Transform ENDP
D3DXVec3TransformArray PROC
    jmp qword ptr [g_real + 2512]
D3DXVec3TransformArray ENDP
D3DXVec3TransformCoord PROC
    jmp qword ptr [g_real + 2520]
D3DXVec3TransformCoord ENDP
D3DXVec3TransformCoordArray PROC
    jmp qword ptr [g_real + 2528]
D3DXVec3TransformCoordArray ENDP
D3DXVec3TransformNormal PROC
    jmp qword ptr [g_real + 2536]
D3DXVec3TransformNormal ENDP
D3DXVec3TransformNormalArray PROC
    jmp qword ptr [g_real + 2544]
D3DXVec3TransformNormalArray ENDP
D3DXVec3Unproject PROC
    jmp qword ptr [g_real + 2552]
D3DXVec3Unproject ENDP
D3DXVec3UnprojectArray PROC
    jmp qword ptr [g_real + 2560]
D3DXVec3UnprojectArray ENDP
D3DXVec4BaryCentric PROC
    jmp qword ptr [g_real + 2568]
D3DXVec4BaryCentric ENDP
D3DXVec4CatmullRom PROC
    jmp qword ptr [g_real + 2576]
D3DXVec4CatmullRom ENDP
D3DXVec4Cross PROC
    jmp qword ptr [g_real + 2584]
D3DXVec4Cross ENDP
D3DXVec4Hermite PROC
    jmp qword ptr [g_real + 2592]
D3DXVec4Hermite ENDP
D3DXVec4Normalize PROC
    jmp qword ptr [g_real + 2600]
D3DXVec4Normalize ENDP
D3DXVec4Transform PROC
    jmp qword ptr [g_real + 2608]
D3DXVec4Transform ENDP
D3DXVec4TransformArray PROC
    jmp qword ptr [g_real + 2616]
D3DXVec4TransformArray ENDP
D3DXWeldVertices PROC
    jmp qword ptr [g_real + 2624]
D3DXWeldVertices ENDP
END
