// GENERATED by tools/locate.py from the installed stellaris.exe. DO NOT EDIT.
// Every value is found by a fingerprint taken from the engine's own code (see the script); rerun it after a game patch.
#pragma once
#include <cstddef>
#include <cstdint>

namespace sdk {
inline constexpr uint32_t kExeTimestamp = 0x6ab5181d;  // PE TimeDateStamp this SDK was located in

namespace fn {
    // void (*)(void* portrait, void* graphics, void* context): renders one visible portrait into its render target
    inline constexpr uintptr_t CPortraitObject_UpdatePortrait = 0xfb1280;
}  // namespace fn

namespace glob {
    // The engine's array of every portrait object (CPdxArray<CPortraitObject*>): RVA of its data pointer and of its int count
    inline constexpr uintptr_t CPortraitObjectController_PortraitObjects_data = 0x287f8b8;
    inline constexpr uintptr_t CPortraitObjectController_PortraitObjects_count = 0x287f8c4;
}  // namespace glob

namespace rt {
    inline constexpr std::ptrdiff_t CPortraitObject_width = 0x528;         // uint16_t, render target width
    inline constexpr std::ptrdiff_t CPortraitObject_height = 0x52a;        // uint16_t, render target height
    inline constexpr std::ptrdiff_t CPortraitObject_needs_render = 0x52c;  // uint8_t, the portrait is re-rendered while set
    inline constexpr std::ptrdiff_t CPortraitObject_render_target = 0x530;  // TextureGFX*, null until first rendered
}  // namespace rt
}  // namespace sdk
