"""Generates the export stubs of the loader (loader/), a proxy of one of the system DLLs the game imports, from the exports of the real DLL:

    python tools/gen_proxy.py [d3dx9_43.dll]

    loader/proxy_exports.def   the export names
    loader/proxy_exports.asm   one `jmp [real function]` stub per export (x64: no signatures needed)
    loader/proxy_names.inc     the names, in the order of the table the stubs jump through, and loader/proxy_dll.inc the DLL's file name

The game must import the DLL, it must not be a KnownDLL, and no system DLL may load it first from System32 (version.dll is pulled in by
SHELL32 before the exe's imports are processed, so a version.dll next to the exe is never picked; d3dx9_43.dll is imported by the exe alone).
Needs `pip install pefile`.
"""
import os
import sys

import pefile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "loader")


def main():
    dll = sys.argv[1] if len(sys.argv) > 1 else "d3dx9_43.dll"
    pe = pefile.PE(os.path.join(os.environ.get("SystemRoot", r"C:\Windows"), "System32", dll), fast_load=True)
    pe.parse_data_directories([pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
    unnamed = [s for s in pe.DIRECTORY_ENTRY_EXPORT.symbols if not s.name]
    if unnamed:
        raise SystemExit(f"{dll} has exports without a name (ordinals {[s.ordinal for s in unnamed]}): not supported")
    names = sorted(s.name.decode() for s in pe.DIRECTORY_ENTRY_EXPORT.symbols)
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "proxy_exports.def"), "w", newline="\n") as f:
        f.write("; GENERATED by tools/gen_proxy.py\nEXPORTS\n" + "".join(f"    {n}\n" for n in names))
    with open(os.path.join(OUT, "proxy_names.inc"), "w", newline="\n") as f:
        f.write("// GENERATED by tools/gen_proxy.py\n" + "".join(f'    "{n}",\n' for n in names))
    with open(os.path.join(OUT, "proxy_dll.inc"), "w", newline="\n") as f:
        f.write(f'// GENERATED by tools/gen_proxy.py\n#define PROXY_DLL_NAME L"{dll}"\n')
    with open(os.path.join(OUT, "proxy_exports.asm"), "w", newline="\n") as f:
        f.write("; GENERATED by tools/gen_proxy.py: each export jumps to the function of the real DLL in g_real\n")
        f.write("EXTERN g_real:QWORD\n.CODE\n")
        for i, n in enumerate(names):
            f.write(f"{n} PROC\n    jmp qword ptr [g_real + {i * 8}]\n{n} ENDP\n")
        f.write("END\n")
    print(f"{dll}: {len(names)} exports written to {OUT}")


if __name__ == "__main__":
    main()
